apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ./service.yaml
  - ./deployment.yaml
  - ./rbac.yaml

# labels:
#   - pairs:
#       role: monitoring
#       owner: java-appteam
#       environment: production
#       batch: k8sb20
#     includeSelectors: false

